//! RP2-family port of the light framework: the RP2040 and the RP2350, one source.
//!
//! Peripherals are driven through the chip's pac register definitions rather than through
//! pico-sdk calls: pico-sdk's peripheral API is mostly `static inline` in headers, which no
//! binding generator can export, so every SDK call from Rust would need a hand-written C shim.
//! The pac reaches everything the framework needs. pico-sdk stays in charge of
//! the RUNTIME (crt0, boot2, clocks, timer start, multicore, USB) in the C shell that links this.
//!
//! One crate for both chips because the blocks this crate touches -- SIO, pads, IO, SPI, I2C,
//! DMA, PWM, the timer -- are the same silicon IP on both, and the two pacs (`rp2040-pac`,
//! `rp235x-pac`) were generated by the same svd2rust generation, so the accessors are
//! identical. The chip is a cargo feature (`rp2040` or `rp2350`, exactly one) and shows in
//! three places: the `pac` alias below, the timer block's name, and the RP2350's pad isolation
//! bit. The Cortex-M0+ adds a fourth, invisible here: it has no atomic read-modify-write
//! instructions, so the framework's atomics are `portable-atomic`'s, which fall back to this
//! crate's critical section on that core and compile to the native instructions on the others.
//!
//! This crate stops at the CHIP. What is soldered to it -- panels, keys, expansion boards --
//! is board wiring, and that belongs to the application: each app carries a `board` module
//! that names its pins, calls the unsafe constructors below exactly once behind a taken-once
//! gate, and hands the peripherals over as an owned set. The framework does not know or care
//! which board anyone runs.

#![no_std]

#[cfg(all(feature = "rp2040", feature = "rp2350"))]
compile_error!("light-rp2: enable exactly one of the `rp2040` and `rp2350` features");
#[cfg(not(any(feature = "rp2040", feature = "rp2350")))]
compile_error!("light-rp2: enable one of the `rp2040` and `rp2350` features");

#[cfg(feature = "rp2040")]
pub use rp2040_pac as pac;
#[cfg(feature = "rp2350")]
pub use rp235x_pac as pac;

//   target-only: the implementation reads PRIMASK and SIO registers, neither of which exists
// where `cargo test` runs this crate's (empty) test harness
#[cfg(target_os = "none")]
mod critical;

pub mod adc;
pub mod gpio;
pub mod i2c;
pub mod i2s;
pub mod pwm;
pub mod pwm_audio;
pub mod qspi;
#[cfg(feature = "rp2350")]
pub mod rgb;
pub mod spi;
pub mod spi_bus;
#[cfg(feature = "usb-host")]
pub mod tinyusb_midi;

use light_core::{Clock, Idle};

/// The clock frequencies the runtime configured, passed in by the shell that knows them rather
/// than assumed here. pico-sdk's defaults are 125 MHz for both on the RP2040, 150 MHz on the
/// RP2350.
#[derive(Clone, Copy, Debug)]
pub struct Clocks {
        pub sys_hz: u32,
        pub peri_hz: u32,
}

/// Microseconds since boot from the 64-bit system timer, which pico-sdk's runtime has already
/// started. The RP2350 has two timer blocks and calls the first TIMER0; the RP2040 has one.
///
/// Read as two halves, re-read until the high half is stable across the low read -- the same
/// dance pico-sdk's `time_us_64()` does, without the latching TIMELR/TIMEHR pair, which is
/// per-core state and would race the other core's use of it.
pub fn now_us() -> u64 {
        #[cfg(feature = "rp2040")]
        let timer = unsafe { &*pac::TIMER::ptr() };
        #[cfg(feature = "rp2350")]
        let timer = unsafe { &*pac::TIMER0::ptr() };
        loop {
                let hi = timer.timerawh().read().bits();
                let lo = timer.timerawl().read().bits();
                if timer.timerawh().read().bits() == hi {
                        return ((hi as u64) << 32) | lo as u64;
                }
        }
}

/// The system timer as a [`Clock`].
#[derive(Clone, Copy, Default)]
pub struct SysClock;

impl Clock for SysClock {
        fn now_us(&self) -> u64 {
                now_us()
        }
}

/// What the runtime does between idle passes on this chip: nothing that could miss a deadline.
/// The poll-driven drivers keep their own cadences and no interrupt is guaranteed to wake a
/// `wfe`, so this is a breath, not a sleep. A real low-power idle needs a tick to wake on.
#[derive(Clone, Copy, Default)]
pub struct Breathe;

impl Idle for Breathe {
        fn idle(&mut self) {
                core::hint::spin_loop();
        }
}
