#   light_mk4_add_font(<name>
#           FONT <file> DISPLAY <name> WIDTH <px> HEIGHT <px> [DIMENSION <WxH mm>]
#           POINT_SIZE <pt> PIXEL_SIZE <px>
#           CRATE <rust crate> ENV <VAR>)
#
#   Renders FONT for the given display with the Rust crush and hands the resulting LGF blob to a
# Rust crate as an environment variable, for `include_bytes!(env!("<VAR>"))`. This is the
# counterpart to the C implementation's crush_add_font_target(): the same one-batch console
# script, but the product is data the firmware embeds rather than C it compiles, and the
# consumer is a cargo build rather than a C target.
#
#   Ordering is the whole point of the function. cargo cannot know a file CMake generates
# exists, so the crate's cargo-build target is made to depend on the render, and the crate sees
# the path through the environment Corrosion passes to cargo. A change to the font file or the
# render parameters re-renders and, because the env var names a file cargo tracks through
# include_bytes!, rebuilds the crate.
function(light_mk4_add_font NAME)
        set(one FONT DISPLAY WIDTH HEIGHT DIMENSION POINT_SIZE PIXEL_SIZE CRATE ENV)
        cmake_parse_arguments(F "" "${one}" "" ${ARGN})
        foreach(req FONT DISPLAY WIDTH HEIGHT POINT_SIZE PIXEL_SIZE CRATE ENV)
                if(NOT DEFINED F_${req})
                        message(FATAL_ERROR "light_mk4_add_font(${NAME}) needs ${req}")
                endif()
        endforeach()
        if(NOT TARGET crush)
                message(FATAL_ERROR "light_mk4_add_font(${NAME}) needs the crush target: import the crush crate with corrosion_set_hostbuild first")
        endif()

        get_filename_component(font_abs "${F_FONT}" ABSOLUTE)
        get_filename_component(font_name "${font_abs}" NAME)
        get_filename_component(font_base "${font_abs}" NAME_WE)
        get_filename_component(font_ext "${font_abs}" EXT)
        string(REGEX REPLACE "^\\." "" font_ext "${font_ext}")

        set(ctx "${CMAKE_CURRENT_BINARY_DIR}/${NAME}.crush_context")
        set(script "${ctx}/${NAME}.crush")
        set(display_line "display add ${F_DISPLAY} ${F_WIDTH} ${F_HEIGHT}")
        if(F_DIMENSION)
                string(APPEND display_line " --dimension ${F_DIMENSION}")
        endif()
        #   context new first: this crush creates nothing by accident, so the batch says so.
        # file(GENERATE) leaves an unchanged script untouched, so a reconfigure does not re-render
        file(GENERATE OUTPUT "${script}" CONTENT
"# generated by light_mk4_add_font(${NAME}) -- do not edit. Runnable by hand: crush console <this file>
context new
font add --local-file \"${font_abs}\"
${display_line}
render new ${NAME} ${F_POINT_SIZE} ${F_PIXEL_SIZE} --font ${font_name} --display ${F_DISPLAY}
")
        set(lgf "${ctx}/.crush/render/${NAME}/${font_base}_${font_ext}_${F_PIXEL_SIZE}px_font.lgf")
        add_custom_command(
                OUTPUT "${lgf}"
                COMMAND ${CMAKE_COMMAND} -E make_directory "${ctx}"
                COMMAND ${CMAKE_COMMAND} -E env CRUSH_CONTEXT= $<TARGET_FILE:crush> console "${script}"
                WORKING_DIRECTORY "${ctx}"
                DEPENDS crush "${font_abs}" "${script}"
                COMMENT "crush: ${NAME} (${font_name} at ${F_PIXEL_SIZE}px for ${F_DISPLAY}) -> LGF"
                VERBATIM
        )
        add_custom_target(${NAME} DEPENDS "${lgf}")

        #   the crate gets the path in its environment and its cargo build waits for the render.
        # cargo-prebuild_<crate> is the hook Corrosion provides for exactly this: work that must
        # finish before cargo is invoked. (cargo-build_<crate> is only the phony wrapper; a
        # dependency on it alone leaves the real cargo command free to run first)
        corrosion_set_env_vars(${F_CRATE} "${F_ENV}=${lgf}")
        add_dependencies(cargo-prebuild_${F_CRATE} ${NAME})
endfunction()
